Build portfolio for mobile version
AbenezerAssefa/Portfolio1 pull request #1
Opened 2022-09-22 08:13 UTC by AbenezerAssefa

For this project I:
 

- Used the [HTML&CSS linter](https://github.com/microverseinc/linters-config/tree/master/html-css)

- Build 2 sections 
    - the toolbar (or header)
    - the headline section (right after the header)    

- Used Flexbox in all 2 sections.

- I sticked to the design as much as possible (e.g. font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).
- Implemented the button interactions (enable, hover, etc.).

2022-09-22 09:39 UTC, awais-amjed requested changes
# STATUS: CHANGES REQUIRED ♻️

Hi @AbenezerAssefa , 

Good job so far! 👏👏
There are some issues that you still need to work on to go to the next project but you are almost there! 🥳🙌🤗

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] Nice Design ✔️
- [x] No Linter issues ✔️ 
- [x] Good code organization ✔️ 

![gif](https://media.giphy.com/media/qLWdMYX1NYF2g/giphy-downsized-large.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-22 09:39 UTC, awais-amjed commented on css/style.css
> +  font-family: var(--font-round);
Kindly note that your `font-family` is not being applied here since you do not have a variable named `font-round`, kindly replace it with something like `'Roboto', sans-serif` or your desired one as you have done above in the `nav p` 🤗

2022-09-22 09:39 UTC, awais-amjed commented on css/style.css
> +  font-family: var(--font-roboto);
Kindly also fix the font family here 🤗

2022-09-22 09:39 UTC, awais-amjed commented on css/style.css
> +  font-family: var(--font-poppins);
Kindly also fix the font family here 🤗

2022-09-22 09:39 UTC, awais-amjed commented on index.html
> +              <p>Abenezer Assefa</p>
Kindly move the logo outside the `nav` tag into the `header` tag and wrap it with an `a` tag for semantic reasons 🤗

2022-09-22 09:39 UTC, awais-amjed commented on index.html
> +            </div>
Kindly reduce the margin on the left a bit and reduce the spacing above these icons to match the Figma design 🤗

Your design:

![image](https://user-images.githubusercontent.com/73714615/191713061-8cefdbf4-6157-4487-93b5-33f88760ef31.png)

Figma design:

![image](https://user-images.githubusercontent.com/73714615/191712916-df77078a-ed0f-48de-9ef7-96597cb0f016.png)

2022-09-22 10:48 UTC, Qoosim approved these changes
#  *Status: Approved* :tada:

Hi @AbenezerAssefa, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

_**Kindly check some optional comments I left under the review**_ :pray: 

## Highlights
 -   No linter errors. :heavy_check_mark:
 -   Good README file. :heavy_check_mark:
 -   Correct GitHub Flow. :heavy_check_mark: 
 -   Good commit messages. :heavy_check_mark: 

![](https://camo.githubusercontent.com/f4e04d5e9518e3cbf972fb0f7611848a87ed4e1aa7770811bc22c5b957824887/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6c3253716972355a78666f5332374576532f67697068792e676966)
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

- [OPTIONAL] Your code kind of broke while trying to implement the requests from the previous reviewer. Your headline text overlapped the decoration background image. Kindly look into it and fix that part. :pray: 

###  Your Design

![your-template](https://user-images.githubusercontent.com/26597432/191726487-8b263480-07a6-427c-92e4-4227ec167191.png)


### Figma Template

![figma-template](https://user-images.githubusercontent.com/26597432/191726535-97bf3b04-ca41-44b2-98f0-fb6da86cdd9c.png)

- [OPTIONAL] Kindly look into the title on your page too. It does not produce the exact outlook as we have it on your chosen Figma template. The font-type and font-weight are not the same with what we have on the Figma template. Kindly look into that too and correct it. :pray: 

### Your Design

![your-header](https://user-images.githubusercontent.com/26597432/191727339-7ace25d9-30f4-4736-9c46-8dd3a4e7a9c1.png)


### Figma Design

![figma-header](https://user-images.githubusercontent.com/26597432/191727385-5fc3d20c-c8b5-440d-b1de-efee98775782.png)

2022-09-22 11:07 UTC, codecaiine reviewed
Hi @AbenezerAssefa , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has already been approved and uses the same PR that was used for **Portfolio: setup and mobile first**. Please make sure that every milestone is implemented in separate branches and a new PR is opened for every submission.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-09-23 14:27 UTC, MaganaAsiati reviewed
# Hi @chuaindia 

made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :negative_squared_cross_mark:

You have submitted a project, but the linter is not properly configured. Follow [this instruction](https://github.com/microverseinc/linters-config/tree/master/html-css#html--css3-course) to configure the linter properly. Make sure that you have installed node  js  to run npm and npx

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏


<img src="https://media0.giphy.com/media/QvMIzHw30MmMAqvOeo/giphy.gif"/>

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
Cheers and Happy coding!👏👏👏
--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2022-09-26 07:56 UTC, topeogunleye requested changes
Hi @AbenezerAssefa, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * Professional README file. :heavy_check_mark:
> * PR has a good summary :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Nothing to mention
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your @topeogunleye so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-26 07:56 UTC, topeogunleye commented on index.html
> +    <section id="projects">
- [ ] As required. I kindly suggest that you ensure that the main container of the projects has a `display:grid`.

2022-09-26 07:56 UTC, topeogunleye commented on index.html
> +         <div class="language-wrap" data-language="language-list">
- [ ] For a list of items, always use the unordered list or `ul` tag and each list item can then be wrapped in a `li`. The list of programming languages thus should be wrapped in a `ul` tag instead of a `div` to maintain its semantic meaning. Kindly alter this code to use an unordered list tag instead.

2022-09-26 07:56 UTC, topeogunleye commented on css/style.css
> +
- [ ] I kindly suggest that you add styles for the state for when the button is pressed. The button has a background color of `#E05304` and text color of ` #F4F1F0`

## EXAMPLE
**for pressed state**
```
button:active {
   background-color: #E05304;
}
```

2022-09-26 07:56 UTC, topeogunleye commented on index.html
> +      <div class="skills">
- [ ] I kindly suggest that you also use a `ul` and create and `li` tag container for your `skills-lang's`

## EXAMPLE
```
   <ul>
        <li class="languague">
              <ul>
                  <li><a href="#">JavaScript</a></li>
                  <li><a href="#">HTML</a>
                  <li><a href="#">CSS</a>
             </ul>
         </li>
          <li class="framework">
              <ul>
                  <li><a href="#">Bootstrap</a></li>
                  <li><a href="#">Ruby on Rails</a>
                  <li><a href="#">RSPEC</a>
             </ul>
         </li>
            <li class="skills">
              <ul>
                  <li><a href="#">Code Kit</a></li>
                  <li><a href="#">GitHub</a>
                  <li><a href="#">Codepen</a>
             </ul>
         </li>                                     
</ul>
```

2022-09-26 14:58 UTC, roshan-bajgain approved these changes
Hi @AbenezerAssefa, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-26 15:07 UTC, merged