Mobile contact
AbenezerAssefa/Portfolio1 pull request #9
Opened 2022-11-01 17:06 UTC by AbenezerAssefa

The Entire Design  of the mobile version of my page is finished 
~I Added a contact form
~ Debugged Markup (HTML)
~ Debugged Style (CSS)
~ Added Formspree configuration 
~ Added Contact Form Validations

2022-11-02 04:44 UTC, HAMMAS-SALEEM reviewed
# Invalid Review Request 🔴

## Hey @AbenezerAssefa, @shakespear95 :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Following Gitflow
✔️ Following some requirements

Good job on implementing some of the requirements, but i cannot proceed review on your pull request, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-02 04:44 UTC, HAMMAS-SALEEM commented on README.md
### Your Summary
![123](https://user-images.githubusercontent.com/93039359/199400046-6d1254fc-e2e5-4f36-a836-deefb05b9a35.PNG)

### Descriptive Summary
![1234](https://user-images.githubusercontent.com/93039359/199400058-76316057-65f3-4a8a-8c6c-0d4845105c83.PNG)

- [ ] You don't have a descriptive summary in your pull request. Kindly make your summary descriptive to make your pull request professional and also to follow the requirements 👍

2022-11-02 04:48 UTC, AbenezerAssefa commented
~I Added a contact form 
~ Debugged Markup (HTML)
~ Debugged Style (CSS)
~ Added Formspree configuration ~ Added Contact Form Validations

2022-11-02 04:52 UTC, HAMMAS-SALEEM reviewed
# Invalid Review Request 🔴

## Hey @AbenezerAssefa, @shakespear95 :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Following Gitflow
✔️ Following some requirements

Good job on implementing some of the requirements, but i cannot proceed review on your pull request, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-02 04:52 UTC, HAMMAS-SALEEM commented on README.md
### Your Summary
![Capture](https://user-images.githubusercontent.com/93039359/199401086-ad4b110c-3633-4fd6-a73c-e1ebd9a9473a.PNG)

### Descriptive Summary
![1234](https://user-images.githubusercontent.com/93039359/199400058-76316057-65f3-4a8a-8c6c-0d4845105c83.PNG)

- [ ] You don't have a descriptive summary in your pull request. Kindly make your summary descriptive to make your pull request professional and also to follow the requirements 👍 
- [ ] You have added the summary at the wrong place because it should be on the top the pull request. Kindly make it descriptive by updating it by clicking on the three dots at as shown in the image 😊

2022-11-02 05:17 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @AbenezerAssefa, @shakespear95 :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
:heavy_check_mark: Descriptive PR Summary
✔️ Following Github flow
✔️ Following some requirements

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-02 05:17 UTC, HAMMAS-SALEEM commented on index.html
> +        </fieldset>
- [ ] Your **textarea** shoud have a **required** attribute on it like the other input fields (**name**, **email**) :+1: so nobody will be able to send you an empty message email :blush:

2022-11-02 05:17 UTC, HAMMAS-SALEEM commented on index.html
> +        </fieldset>
![contact-form-white-spacing](https://user-images.githubusercontent.com/93039359/199403575-47248e32-ac0e-4864-846e-b504ca63375c.png)

- [ ] You can see that your contents are not in center. :fearful: Its because you have a horizontal scrollbar. Kindly fix that issue to make your contents aligned in the center :blush:

2022-11-02 05:17 UTC, HAMMAS-SALEEM commented on index.html
> +      <h2>
- [ ] Kindly use **footer** tag instead of **section** tag to follow the HTML semantic tags due to SEO purpose :+1:

2022-11-02 05:45 UTC, HAMMAS-SALEEM approved these changes
# Status: Approved :green_circle: :1st_place_medal: :100:
![success](https://camo.githubusercontent.com/6ada59f6189497c1c2cae6d06f8154b7307a58643f232340e288140ed469eb28/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966)

## Hey @AbenezerAssefa, @shakespear95 :wave:

Great work on implementing the requested changes. Your project is complete. :blush:
There is nothing else to say about your project. :+1:

## Highlights :1st_place_medal:

:heavy_check_mark: Descriptive PR Title
:heavy_check_mark: Descriptive PR Summary
:heavy_check_mark: Following Github Flow
:heavy_check_mark: Following Requirements

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-02 05:57 UTC, merged

2022-11-07 08:11 UTC, sajid-munawar reviewed
### Hi @AbenezerAssefa , 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and description :heavy_check_mark:
 
 ## [Optional] suggestions:
 * [ ]  Please check my inline comments.

 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._